/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pestañas;

import Login.puntaje;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author Usuario
 */
public class puntajeFinal extends javax.swing.JFrame {

    /**
     * Creates new form puntajeFinal
     */
    public puntajeFinal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsalirjuego = new javax.swing.JButton();
        btnpuntajefinal = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gracias por participar y jugar. Vamos a seguir mejorando en el juego.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 660, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/g.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 400, 160));

        btnsalirjuego.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsalirjuego.setText("Salir");
        btnsalirjuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirjuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalirjuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 110, 60));

        btnpuntajefinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnpuntajefinal.setText("Su puntaje final es:");
        btnpuntajefinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntajefinalActionPerformed(evt);
            }
        });
        getContentPane().add(btnpuntajefinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 396));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirjuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirjuegoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirjuegoActionPerformed

    private void btnpuntajefinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntajefinalActionPerformed
        puntaje pu = new puntaje();
        pu.equals(pu);
        JOptionPane.showMessageDialog(null, "Su puntaje final fue: " + pu);
        
    }//GEN-LAST:event_btnpuntajefinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puntajeFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puntajeFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puntajeFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puntajeFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puntajeFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpuntajefinal;
    private javax.swing.JButton btnsalirjuego;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
