/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pestañas;

/**
 *
 * @author Usuario
 */

import java.util.Scanner;
import javax.swing.JOptionPane;

public class segundapartepestaña4 extends javax.swing.JFrame {

    /**
     * Creates new form segundapartepestaña4
     */
    public segundapartepestaña4() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chexboxRespuesta1 = new javax.swing.JCheckBox();
        chexboxRespuesta2 = new javax.swing.JCheckBox();
        chexboxRespuesta3 = new javax.swing.JCheckBox();
        btnsiguiente = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pregunta 4 Parte 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 190, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/poo.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 300, 280));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¿Qué es un lenguaje orientado a objetos?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        buttonGroup1.add(chexboxRespuesta1);
        chexboxRespuesta1.setForeground(new java.awt.Color(255, 255, 255));
        chexboxRespuesta1.setText("Crean un sistema de clases y objetos siguiendo el esquema del mundo real para definir los objetos, acciones y forma de comunican entre objetos.");
        getContentPane().add(chexboxRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        buttonGroup1.add(chexboxRespuesta2);
        chexboxRespuesta2.setForeground(new java.awt.Color(255, 255, 255));
        chexboxRespuesta2.setText("Permiten la implementación de prácticamente cualquier algoritmo, el nivel de abstracción es más uniforme");
        getContentPane().add(chexboxRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        buttonGroup1.add(chexboxRespuesta3);
        chexboxRespuesta3.setForeground(new java.awt.Color(255, 255, 255));
        chexboxRespuesta3.setText("Aquellos en los cuales se le ordena a el ordenador cómo realizar una tarea siguiendo una serie de pasos o instrucciones.");
        getContentPane().add(chexboxRespuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        btnsiguiente.setBackground(new java.awt.Color(0, 0, 0));
        btnsiguiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnsiguiente.setText("Siguiente");
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, 30));

        btnsalir.setBackground(new java.awt.Color(0, 0, 0));
        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 90, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        // TODO add your handling code here:
        segundapartepestaña5 p = new segundapartepestaña5();
     p.setVisible(true);
     this.dispose();
     segundapartepestaña4();
    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void segundapartepestaña4(){
         
     String pregunta ;
     String respuesta;
     
     int puntaje=0;
    
  
     Scanner entrada = new Scanner(System.in);
  
        if (chexboxRespuesta1.isSelected()){
             puntaje=+1;
            JOptionPane.showMessageDialog(null, "Respuesta Inorrecta" , "Suerte en la siguiente. ", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Respuesta Inorrecta, Suerte en la siguiente. ");
            } 
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(segundapartepestaña4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(segundapartepestaña4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(segundapartepestaña4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(segundapartepestaña4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new segundapartepestaña4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chexboxRespuesta1;
    private javax.swing.JCheckBox chexboxRespuesta2;
    private javax.swing.JCheckBox chexboxRespuesta3;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
